//List<String> countryList = ['Country 1', 'Country 2', 'Country 3']; // Add your actual country names here


const List<Map<String, dynamic>> countryList = [
  {"countryCode": "af", "fullName": "Afghanistan"},
  {"countryCode": "al", "fullName": "Albania"},
  {"countryCode": "dz", "fullName": "Algeria"},
  {"countryCode": "as", "fullName": "American Samoa"},
  {"countryCode": "ad", "fullName": "Andorra"},
  {"countryCode": "ao", "fullName": "Angola"},
  {"countryCode": "ai", "fullName": "Anguilla"},
  {"countryCode": "aq", "fullName": "Antarctica"},
  {"countryCode": "ag", "fullName": "Antigua and Barbuda"},
  {"countryCode": "ar", "fullName": "Argentina"},
  {"countryCode": "am", "fullName": "Armenia"},
  {"countryCode": "aw", "fullName": "Aruba"},
  {"countryCode": "au", "fullName": "Australia"},
  {"countryCode": "at", "fullName": "Austria"},
  {"countryCode": "az", "fullName": "Azerbaijan"},
  {"countryCode": "bs", "fullName": "Bahamas"},
  {"countryCode": "bh", "fullName": "Bahrain"},
  {"countryCode": "bd", "fullName": "Bangladesh"},
  {"countryCode": "bb", "fullName": "Barbados"},
  {"countryCode": "by", "fullName": "Belarus"},
  {"countryCode": "be", "fullName": "Belgium"},
  {"countryCode": "bz", "fullName": "Belize"},
  {"countryCode": "bj", "fullName": "Benin"},
  {"countryCode": "bm", "fullName": "Bermuda"},
  {"countryCode": "bt", "fullName": "Bhutan"},
  {"countryCode": "bo", "fullName": "Bolivia"},
  {"countryCode": "bq", "fullName": "Bonaire, Sint Eustatius..."},
  {"countryCode": "ba", "fullName": "Bosnia and Herzegovina"},
  {"countryCode": "bw", "fullName": "Botswana"},
  {"countryCode": "bv", "fullName": "Bouvet Island"},
  {"countryCode": "br", "fullName": "Brazil"},
  {"countryCode": "io", "fullName": "British Indian Ocean T..."},
  {"countryCode": "bn", "fullName": "Brunei Darussalam"},
  {"countryCode": "bg", "fullName": "Bulgaria"},
  {"countryCode": "bf", "fullName": "Burkina Faso"},
  {"countryCode": "bi", "fullName": "Burundi"},
  {"countryCode": "cv", "fullName": "Cabo Verde"},
  {"countryCode": "kh", "fullName": "Cambodia"},
  {"countryCode": "cm", "fullName": "Cameroon"},
  {"countryCode": "ca", "fullName": "Canada"},
  {"countryCode": "ky", "fullName": "Cayman Islands"},
  {"countryCode": "cf", "fullName": "Central African Republic"},
  {"countryCode": "td", "fullName": "Chad"},
  {"countryCode": "cl", "fullName": "Chile"},
  {"countryCode": "cn", "fullName": "China"},
  {"countryCode": "cx", "fullName": "Christmas Island"},
  {"countryCode": "cc", "fullName": "Cocos (Keeling) Islands"},
  {"countryCode": "co", "fullName": "Colombia"},
  {"countryCode": "km", "fullName": "Comoros"},
  {"countryCode": "cd", "fullName": "Congo"},
  {"countryCode": "cg", "fullName": "Congo, Democratic Rep..."},
  {"countryCode": "ck", "fullName": "Cook Islands"},
  {"countryCode": "cr", "fullName": "Costa Rica"},
  {"countryCode": "hr", "fullName": "Croatia"},
  {"countryCode": "cu", "fullName": "Cuba"},
  {"countryCode": "cw", "fullName": "Curaçao"},
  {"countryCode": "cy", "fullName": "Cyprus"},
  {"countryCode": "cz", "fullName": "Czechia"},
  {"countryCode": "ci", "fullName": "Côte d'Ivoire"},
  {"countryCode": "dk", "fullName": "Denmark"},
  {"countryCode": "dj", "fullName": "Djibouti"},
  {"countryCode": "dm", "fullName": "Dominica"},
  {"countryCode": "do", "fullName": "Dominican Republic"},
  {"countryCode": "ec", "fullName": "Ecuador"},
  {"countryCode": "eg", "fullName": "Egypt"},
  {"countryCode": "sv", "fullName": "El Salvador"},
  {"countryCode": "gq", "fullName": "Equatorial Guinea"},
  {"countryCode": "er", "fullName": "Eritrea"},
  {"countryCode": "ee", "fullName": "Estonia"},
  {"countryCode": "sz", "fullName": "Eswatini"},
  {"countryCode": "et", "fullName": "Ethiopia"},
  {"countryCode": "fk", "fullName": "Falkland Islands"},
  {"countryCode": "fo", "fullName": "Faroe Islands"},
  {"countryCode": "fj", "fullName": "Fiji"},
  {"countryCode": "fi", "fullName": "Finland"},
  {"countryCode": "fr", "fullName": "France"},
  {"countryCode": "gf", "fullName": "French Guiana"},
  {"countryCode": "pf", "fullName": "French Polynesia"},
  {"countryCode": "tf", "fullName": "French Southern Terr..."},
  {"countryCode": "ga", "fullName": "Gabon"},
  {"countryCode": "gm", "fullName": "Gambia"},
  {"countryCode": "ge", "fullName": "Georgia"},
  {"countryCode": "de", "fullName": "Germany"},
  {"countryCode": "gh", "fullName": "Ghana"},
  {"countryCode": "gi", "fullName": "Gibraltar"},
  {"countryCode": "gr", "fullName": "Greece"},
  {"countryCode": "gl", "fullName": "Greenland"},
  {"countryCode": "gd", "fullName": "Grenada"},
  {"countryCode": "gp", "fullName": "Guadeloupe"},
  {"countryCode": "gu", "fullName": "Guam"},
  {"countryCode": "gt", "fullName": "Guatemala"},
  {"countryCode": "gg", "fullName": "Guernsey"},
  {"countryCode": "gn", "fullName": "Guinea"},
  {"countryCode": "gw", "fullName": "Guinea-Bissau"},
  {"countryCode": "gy", "fullName": "Guyana"},
  {"countryCode": "ht", "fullName": "Haiti"},
  {"countryCode": "hm", "fullName": "Heard Island and Mc..."},
  {"countryCode": "va", "fullName": "Holy See"},
  {"countryCode": "hn", "fullName": "Honduras"},
  {"countryCode": "hk", "fullName": "Hong Kong"},
  {"countryCode": "hu", "fullName": "Hungary"},
  {"countryCode": "is", "fullName": "Iceland"},
  {"countryCode": "in", "fullName": "India"},
  {"countryCode": "id", "fullName": "Indonesia"},
  {"countryCode": "ir", "fullName": "Iran, Islamic Rep..."},
  {"countryCode": "iq", "fullName": "Iraq"},
  {"countryCode": "ie", "fullName": "Ireland"},
  {"countryCode": "im", "fullName": "Isle of Man"},
  {"countryCode": "il", "fullName": "Israel"},
  {"countryCode": "it", "fullName": "Italy"},
  {"countryCode": "jm", "fullName": "Jamaica"},
  {"countryCode": "jp", "fullName": "Japan"},
  {"countryCode": "je", "fullName": "Jersey"},
  {"countryCode": "jo", "fullName": "Jordan"},
  {"countryCode": "kz", "fullName": "Kazakhstan"},
  {"countryCode": "ke", "fullName": "Kenya"},
  {"countryCode": "ki", "fullName": "Kiribati"},
  {"countryCode": "kp", "fullName": "Korea, Democratic P..."},
  {"countryCode": "kr", "fullName": "Korea, Republic of"},
  {"countryCode": "kw", "fullName": "Kuwait"},
  {"countryCode": "kg", "fullName": "Kyrgyzstan"},
  {"countryCode": "la", "fullName": "Lao People's Democratic..."},
  {"countryCode": "lv", "fullName": "Latvia"},
  {"countryCode": "lb", "fullName": "Lebanon"},
  {"countryCode": "ls", "fullName": "Lesotho"},
  {"countryCode": "lr", "fullName": "Liberia"},
  {"countryCode": "ly", "fullName": "Libya"},
  {"countryCode": "li", "fullName": "Liechtenstein"},
  {"countryCode": "lt", "fullName": "Lithuania"},
  {"countryCode": "lu", "fullName": "Luxembourg"},
  {"countryCode": "mo", "fullName": "Macao"},
  {"countryCode": "mg", "fullName": "Madagascar"},
  {"countryCode": "mw", "fullName": "Malawi"},
  {"countryCode": "my", "fullName": "Malaysia"},
  {"countryCode": "mv", "fullName": "Maldives"},
  {"countryCode": "ml", "fullName": "Mali"},
  {"countryCode": "mt", "fullName": "Malta"},
  {"countryCode": "mh", "fullName": "Marshall Islands"},
  {"countryCode": "mq", "fullName": "Martinique"},
  {"countryCode": "mr", "fullName": "Mauritania"},
  {"countryCode": "mu", "fullName": "Mauritius"},
  {"countryCode": "yt", "fullName": "Mayotte"},
  {"countryCode": "mx", "fullName": "Mexico"},
  {"countryCode": "fm", "fullName": "Micronesia"},
  {"countryCode": "md", "fullName": "Moldova"},
  {"countryCode": "mc", "fullName": "Monaco"},
  {"countryCode": "mn", "fullName": "Mongolia"},
  {"countryCode": "me", "fullName": "Montenegro"},
  {"countryCode": "ms", "fullName": "Montserrat"},
  {"countryCode": "ma", "fullName": "Morocco"},
  {"countryCode": "mz", "fullName": "Mozambique"},
  {"countryCode": "mm", "fullName": "Myanmar"},
  {"countryCode": "na", "fullName": "Namibia"},
  {"countryCode": "nr", "fullName": "Nauru"},
  {"countryCode": "np", "fullName": "Nepal"},
  {"countryCode": "nl", "fullName": "Netherlands"},
  {"countryCode": "nc", "fullName": "New Caledonia"},
  {"countryCode": "nz", "fullName": "New Zealand"},
  {"countryCode": "ni", "fullName": "Nicaragua"},
  {"countryCode": "ne", "fullName": "Niger"},
  {"countryCode": "ng", "fullName": "Nigeria"},
  {"countryCode": "nu", "fullName": "Niue"},
  {"countryCode": "nf", "fullName": "Norfolk Island"},
  {"countryCode": "mp", "fullName": "Northern Mariana Islands"},
  {"countryCode": "no", "fullName": "Norway"},
  {"countryCode": "om", "fullName": "Oman"},
  {"countryCode": "pk", "fullName": "Pakistan"},
  {"countryCode": "pw", "fullName": "Palau"},
  {"countryCode": "ps", "fullName": "Palestine"},
  {"countryCode": "pa", "fullName": "Panama"},
  {"countryCode": "pg", "fullName": "Papua New Guinea"},
  {"countryCode": "py", "fullName": "Paraguay"},
  {"countryCode": "pe", "fullName": "Peru"},
  {"countryCode": "ph", "fullName": "Philippines"},
  {"countryCode": "pn", "fullName": "Pitcairn"},
  {"countryCode": "pl", "fullName": "Poland"},
  {"countryCode": "pt", "fullName": "Portugal"},
  {"countryCode": "pr", "fullName": "Puerto Rico"},
  {"countryCode": "qa", "fullName": "Qatar"},
  {"countryCode": "mk", "fullName": "Republic of North Mac..."},
  {"countryCode": "ro", "fullName": "Romania"},
  {"countryCode": "ru", "fullName": "Russia"},
  {"countryCode": "rw", "fullName": "Rwanda"},
  {"countryCode": "re", "fullName": "Réunion"},
  {"countryCode": "bl", "fullName": "Saint Barthélemy"},
  {"countryCode": "sh", "fullName": "Saint Helena"},
  {"countryCode": "kn", "fullName": "Saint Kitts and Nevis"},
  {"countryCode": "lc", "fullName": "Saint Lucia"},
  {"countryCode": "mf", "fullName": "Saint Martin"},
  {"countryCode": "pm", "fullName": "Saint Pierre and Miquelon"},
  {"countryCode": "vc", "fullName": "Saint Vincent and..."},
  {"countryCode": "ws", "fullName": "Samoa"},
  {"countryCode": "sm", "fullName": "San Marino"},
  {"countryCode": "st", "fullName": "Sao Tome and Principe"},
  {"countryCode": "sa", "fullName": "Saudi Arabia"},
  {"countryCode": "sn", "fullName": "Senegal"},
  {"countryCode": "rs", "fullName": "Serbia"},
  {"countryCode": "sc", "fullName": "Seychelles"},
  {"countryCode": "sl", "fullName": "Sierra Leone"},
  {"countryCode": "sg", "fullName": "Singapore"},
  {"countryCode": "sx", "fullName": "Sint Maarten"},
  {"countryCode": "sk", "fullName": "Slovakia"},
  {"countryCode": "si", "fullName": "Slovenia"},
  {"countryCode": "sb", "fullName": "Solomon Islands"},
  {"countryCode": "so", "fullName": "Somalia"},
  {"countryCode": "za", "fullName": "South Africa"},
  {"countryCode": "gs", "fullName": "South Georgia and..."},
  {"countryCode": "ss", "fullName": "South Sudan"},
  {"countryCode": "es", "fullName": "Spain"},
  {"countryCode": "lk", "fullName": "Sri Lanka"},
  {"countryCode": "sd", "fullName": "Sudan"},
  {"countryCode": "sr", "fullName": "Suriname"},
  {"countryCode": "sj", "fullName": "Svalbard and Jan Mayen"},
  {"countryCode": "se", "fullName": "Sweden"},
  {"countryCode": "ch", "fullName": "Switzerland"},
  {"countryCode": "sy", "fullName": "Syria"},
  {"countryCode": "tw", "fullName": "Taiwan"},
  {"countryCode": "tj", "fullName": "Tajikistan"},
  {"countryCode": "tz", "fullName": "Tanzania"},
  {"countryCode": "th", "fullName": "Thailand"},
  {"countryCode": "tl", "fullName": "Timor-Leste"},
  {"countryCode": "tg", "fullName": "Togo"},
  {"countryCode": "tk", "fullName": "Tokelau"},
  {"countryCode": "to", "fullName": "Tonga"},
  {"countryCode": "tt", "fullName": "Trinidad and Tobago"},
  {"countryCode": "tn", "fullName": "Tunisia"},
  {"countryCode": "tr", "fullName": "Turkey"},
  {"countryCode": "tm", "fullName": "Turkmenistan"},
  {"countryCode": "tc", "fullName": "Turks and Caicos Islands"},
  {"countryCode": "tv", "fullName": "Tuvalu"},
  {"countryCode": "ug", "fullName": "Uganda"},
  {"countryCode": "ua", "fullName": "Ukraine"},
  {"countryCode": "ae", "fullName": "United Arab Emirates"},
  {"countryCode": "gb", "fullName": "United Kingdom"},
  {"countryCode": "um", "fullName": "United States Minor..."},
  {"countryCode": "us", "fullName": "United States of America"},
  {"countryCode": "uy", "fullName": "Uruguay"},
  {"countryCode": "uz", "fullName": "Uzbekistan"},
  {"countryCode": "vu", "fullName": "Vanuatu"},
  {"countryCode": "ve", "fullName": "Venezuela"},
  {"countryCode": "vn", "fullName": "Vietnam"},
  {"countryCode": "vg", "fullName": "Virgin Islands (British)"},
  {"countryCode": "vi", "fullName": "Virgin Islands (U.S.)"},
  {"countryCode": "wf", "fullName": "Wallis and Futuna"},
  {"countryCode": "eh", "fullName": "Western Sahara"},
  {"countryCode": "ye", "fullName": "Yemen"},
  {"countryCode": "zm", "fullName": "Zambia"},
  {"countryCode": "zw", "fullName": "Zimbabwe"},
];